service: sport-subscriber-api

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    USER_TABLE: ${self:service}-${opt:stage, 'dev'}-user_table
  role: arn:aws:iam::964575162768:role/Sports-Subscriber-LambdaRole
  iamManagedPolicies:
    - arn:aws:iam::964575162768:policy/Sports-Subscriber-LambdaPolicy

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dynamodb-local

custom:
  tableName: ${self:service}-${opt:stage, 'dev'}-user_table
  dynamodb:
    start:
      migrate: true

resources:
  Resources:
    userTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.USER_TABLE}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
